const Themes = {
    lightTheme: {
        //light theme colors
        COLOR_THEME: 'light',
        COLOR_PRIMARY: 'blue',
        COLOR_BACKGROUND: '#E3E3E3',
        COLOR_CARD: '#FAFAFA',
        COLOR_FONT:'#1c1e21',

        COLOR_SECONDARY: '#111',
        COLOR_WHITE: '#FFFFFF',
        COLOR_BLACK: '#000000',
        COLOR_GREY: 'grey',
        COLOR_GREEN: 'green',
        COLOR_PLACEHOLDER: '#111111',
        COLOR_GREY_WHITE: '#FAFAFA',
        COLOR_DARK_SEPERATOR: '#D4D4D4',
        COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.7)',
        COLOR_GREY_TRANSP: 'rgba(67, 85, 85, 0.7)',

    //     COLOR_PRIMARY: '#00E3BA',
    // COLOR_BACKGROUND: '#FAFAFA',
    COLOR_BORDER: '#E5E5E5',
    COLOR_SHADOW: '#E5E5E5',
    COLOR_GRAY_LIGHT: '#E5E5E5',
    COLOR_GRAY: '#CCCCCC',
    COLOR_GRAY_DARK: '#979797',
    COLOR_BLACK_LIGHT: '#353638',
    COLOR_BLACK: '#222222',
    COLOR_BLACK_DARK: '#111111',
    COLOR_WHITE: '#FAFAFA',
    COLOR_WHITE_DARK: '#FFFFFF',
    COLOR_ACTIVE: '#314743',
    COLOR_ACTIVE_RED: '#FF0B46',
    COLOR_ACTIVE_BLUE: '#35B3FF',
    COLOR_INACTIVE: '#6C6C6C',
    COLOR_PINK: '#F86486',
    COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.15)',
    },
    darkTheme: {
        //dark theme colors
        COLOR_THEME: 'dark',
        COLOR_PRIMARY: 'red',
        COLOR_BACKGROUND: '#20232a',
        COLOR_CARD: '#1b1b1d',
        COLOR_FONT:'#e3e3e3',

        COLOR_SECONDARY: '#111',
        COLOR_WHITE: '#FFFFFF',
        COLOR_BLACK: '#000000',
        COLOR_GREY: 'grey',
        COLOR_GREEN: 'green',
        COLOR_PLACEHOLDER: '#111111',
        COLOR_GREY_WHITE: '#FAFAFA',
        COLOR_DARK_SEPERATOR: '#D4D4D4',
        COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.7)',
        COLOR_GREY_TRANSP: 'rgba(67, 85, 85, 0.7)',

    //     COLOR_PRIMARY: '#00E3BA',
    // COLOR_BACKGROUND: '#FAFAFA',
    COLOR_BORDER: '#E5E5E5',
    COLOR_SHADOW: '#E5E5E5',
    COLOR_GRAY_LIGHT: '#E5E5E5',
    COLOR_GRAY: '#CCCCCC',
    COLOR_GRAY_DARK: '#979797',
    COLOR_BLACK_LIGHT: '#353638',
    COLOR_BLACK: '#222222',
    COLOR_BLACK_DARK: '#111111',
    COLOR_WHITE: '#FAFAFA',
    COLOR_WHITE_DARK: '#FFFFFF',
    COLOR_ACTIVE: '#314743',
    COLOR_ACTIVE_RED: '#FF0B46',
    COLOR_ACTIVE_BLUE: '#35B3FF',
    COLOR_INACTIVE: '#6C6C6C',
    COLOR_PINK: '#F86486',
    COLOR_BLACK_TRANSP: 'rgba(0, 0, 0, 0.15)',
    },
    //common colors
};
export default Themes;