const data=[
    {
        id: 'bd7a12cbeam',
        title: 'Sundar kumar',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',

      },
      {
        id: 'bd0ac34b5eaj',
        title: 'Kishan Gupta',
        amount:30400,
        category:'soft',
        type:'MIDIUM',
        maxCapacity:530000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',

      },
      {
        id: '3agc68afc534',
        title: 'Rakesh Chalke',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '58643954a0f',
        title: 'Dinesh Pawar',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '3ac6a856666va907fc',
        title: 'Ashutosh Bhuwad',
        amount:3000,
        category:'soft',
        type:'HIGH',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '586e594adfvfdv0f',
        title: 'Keaivalya kadam',
        amount:3000,
        category:'soft',
        type:'MEDIUM',
        maxCapacity:23000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'indirect',
        mobile_number_primary:'9021010551',
      },
      {
        id: '3ac68eawf5afc',
        title: 'Jagdish khapre',
        amount:3000,
        category:'soft',
        type:'HIGH',
        maxCapacity:6500,
        minCapacity:500,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '585694werwea0f',
        title: 'Pawan kumar',
        amount:3000,
        category:'soft',
        type:'MEDIUM',
        maxCapacity:90000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: 'bd7acbewrewea3',
        title: 'Sundar kumar',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',

      },
      {
        id: 'bd0wwweeacb5wea',
        title: 'Kishan Gupta',
        amount:30400,
        category:'soft',
        type:'MIDIUM',
        maxCapacity:530000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',

      },
      {
        id: '3ac68afycyhtyh5',
        title: 'Rakesh Chalke',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '586954ar0rgtrf',
        title: 'Dinesh Pawar',
        amount:3000,
        category:'soft',
        type:'NORMAL',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '3ac6e85afc65gh',
        title: 'Ashutosh Bhuwad',
        amount:3000,
        category:'soft',
        type:'HIGH',
        maxCapacity:50000,
        minCapacity:1000,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '58e6594a0fwaswq',
        title: 'Keaivalya kadam',
        amount:3000,
        category:'soft',
        type:'MEDIUM',
        maxCapacity:23000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'indirect',
        mobile_number_primary:'9021010551',
      },
      {
        id: '3ac6e85afcwwefgg',
        title: 'Jagdish khapre',
        amount:3000,
        category:'soft',
        type:'HIGH',
        maxCapacity:6500,
        minCapacity:500,
        dependant:false,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
      {
        id: '585694da0fgtrh',
        title: 'Pawan kumar',
        amount:3000,
        category:'soft',
        type:'MEDIUM',
        maxCapacity:90000,
        minCapacity:1000,
        dependant:true,
        isTaken:null,
        source:'direct',
        mobile_number_primary:'9021010551',
      },
]
export default data;